### Signup
POST http://localhost:8080/uni-api/auth/signup
Content-Type: application/json

{
  "username": "ali@gmail.com",
  "password": "123456789"
}

### Login
POST http://localhost:8080/uni-api/auth/login
Content-Type: application/json

{
  "username": "a@gmail.com",
  "password": ""
}