### Test
GET http://localhost:8080/uni-api/Hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJ1c2VybmFtZSI6InhAZ21haWwuY29tIiwiaWF0IjoxNjkyNDgwNjU2LCJleHAiOjE3MDgzODkwNTYsImlzcyI6InNwcmluZy1kZW1vL3Jlc3QtYXBpL3VuaS1hcGkifQ.YE3uq8rTyF38_KR9y-7i46yGHjz6QwCpr75qNUFHlp8